version: '2.1'

services:
  #service 1: mysql database image creation
  db:
    image: mysql
    container_name: mysqlforapp
    environment:
      - MYSQL_ROOT_PASSWORD=spring
      - MYSQL_DATABASE=mydb
    ports:
      - "3306:3306"
#    restart: always
    networks:
      - lotus
    restart: on-failure
  web-app:
      container_name: springboot-web
      image: springboot-web
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - "8080:8080"
      depends_on:
        - mysqldb
      networks:
        - lotus
      environment:
        - APP_MYSQL_DATASOURCE_URL=jdbc:mysql://mysqlforapp:3306/mydb
        - APP_MYSQL_USERNAME=user
        - APP_MYSQL_PASSWORD=1234
      restart: on-failure

  networks:
      lotus:
        name: lotus