version: '2.1'

services:
  #service 1: mysql database image creation
  db:
    image: mysql
    container_name: appdb
    environment:
      - MYSQL_ROOT_PASSWORD=spring
      - MYSQL_DATABASE=shedule
    ports:
      - "3306:3306"
#    restart: always
    networks:
      - lotus
    restart: on-failure
  web-app:
      container_name: springboot-web
      image: springboot-web
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - "8080:8080"
      depends_on:
        - db
      networks:
        - lotus
      environment:
        - APP_MYSQL_DATASOURCE_URL=jdbc:db://appdb:3306/shedule
        - APP_MYSQL_USERNAME=root
        - APP_MYSQL_PASSWORD=spring
      restart: on-failure

networks:
  lotus:
      name: lotus