spring:
  datasource:
    url: ${APP_MYSQL_DATASOURCE_URL:jdbc:mysql://localhost:3306/shedule}
    username: ${APP_MYSQL_USERNAME:root}
    password: ${APP_MYSQL_PASSWORD:spring}

    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#    database-platform: org.hibernate.dialect.MySQL8Dialect